spring.application.name=Device Config Change Notification API

spring.datasource.url = jdbc:mysql://localhost:3306/devices_db
spring.datasource.username = root
spring.datasource.password = Pranjal7007
spring.datasource.driver.hibernate.format_sql = true

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true



